name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ange den version du använder

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --ci --silent --coverage

      - name: Build the project
        run: npm run build

      - name: Upload coverage report
        if: success() && steps.test.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage
